# WARNING : Any changes to this config file will not take effect!!
# To fix this, set 'IGNORE_CONFIG_FILE: true' --> 'IGNORE_CONFIG_FILE: false'
# This was done to prevent default values in new versions from being overriden
# by outdated config files. By doing this, you will no longer recieve any new
# config defaults...

IGNORE_CONFIG_FILE: true

benderSettings:
  maxLevel: 7
  maxNumberOfBenders: 3
bisonFoods: {}
bisonSettings:
  bisonBreedMaxMinutes: 120.0
  bisonBreedMinMinutes: 60.0
  bisonChestTameness: 1000
  bisonGrassFoodBonus: 5
  bisonLeashTameness: 1000
  bisonMaxDomestication: 800
  bisonMinDomestication: 500
  bisonOwnableTameness: 900
  bisonRideOneSecondTameness: 3
  bisonRiderTameness: 800
scrollDropChance: {}
scrollSettings:
  absoluteChaos: false
  chaos: false
  numberChanceDecreaseMult: 0.6666666865348816
  percentPerNumber: 10.0
  percentPerTier: 10.0
  tierChanceDecreaseMult: 0.5
scrollTradeItems: {}
scrollType: {}
