import mods.thermalexpansion.Transposer;
//remove

recipes.remove(<industrialforegoing:range_addon:11>);
recipes.remove(<industrialforegoing:range_addon:10>);
recipes.remove(<industrialforegoing:range_addon:9>);
recipes.remove(<industrialforegoing:range_addon:8>);
recipes.remove(<industrialforegoing:range_addon:7>);
recipes.remove(<industrialforegoing:range_addon:6>);
recipes.remove(<industrialforegoing:range_addon:5>);
recipes.remove(<industrialforegoing:range_addon:4>);
recipes.remove(<industrialforegoing:range_addon:3>);
recipes.remove(<industrialforegoing:range_addon:2>);
recipes.remove(<industrialforegoing:range_addon:1>);
recipes.remove(<industrialforegoing:range_addon>);
recipes.remove(<industrialforegoing:conveyor>);
recipes.remove(<industrialforegoing:adult_filter>);
recipes.remove(<industrialforegoing:energy_field_addon>);
recipes.remove(<industrialforegoing:leaf_shearing>);
recipes.remove(<industrialforegoing:fortune_addon>);
recipes.remove(<industrialforegoing:meat_feeder>);
recipes.remove(<industrialforegoing:mob_imprisonment_tool>);
recipes.remove(<industrialforegoing:conveyor_upgrade>);
recipes.remove(<industrialforegoing:conveyor_upgrade:1>);
recipes.remove(<industrialforegoing:conveyor_upgrade:2>);
recipes.remove(<industrialforegoing:conveyor_upgrade:3>);
recipes.remove(<industrialforegoing:conveyor_upgrade:4>);
recipes.remove(<industrialforegoing:conveyor_upgrade:5>);
recipes.remove(<industrialforegoing:conveyor_upgrade:6>);
recipes.remove(<industrialforegoing:crop_sower>);
recipes.remove(<industrialforegoing:animal_stock_increaser>);
recipes.remove(<industrialforegoing:animal_independence_selector>);
recipes.remove(<industrialforegoing:potion_enervator>);
recipes.remove(<industrialforegoing:mob_relocator>);
recipes.remove(<industrialforegoing:enchantment_aplicator>);
recipes.remove(<industrialforegoing:enchantment_extractor>);
recipes.remove(<industrialforegoing:enchantment_refiner>);
recipes.remove(<industrialforegoing:petrified_fuel_generator>);
recipes.remove(<industrialforegoing:spores_recreator>);
recipes.remove(<industrialforegoing:enchantment_invoker>);
recipes.remove(<industrialforegoing:dye_mixer>);
recipes.remove(<industrialforegoing:black_hole_tank>);
recipes.remove(<industrialforegoing:material_stonework_factory>);
recipes.remove(<industrialforegoing:animal_growth_increaser>);
recipes.remove(<industrialforegoing:fluid_crafter>);
recipes.remove(<industrialforegoing:plant_interactor>);
recipes.remove(<industrialforegoing:item_splitter>);
recipes.remove(<industrialforegoing:animal_resource_harvester>);
recipes.remove(<industrialforegoing:fluid_pump>);
recipes.remove(<industrialforegoing:wither_builder>);
recipes.remove(<industrialforegoing:hydrator>);
recipes.remove(<industrialforegoing:protein_generator>);
recipes.remove(<industrialforegoing:oredictionary_converter>);
recipes.remove(<industrialforegoing:ore_fermenter>);
recipes.remove(<industrialforegoing:protein_reactor>);
recipes.remove(<industrialforegoing:pitiful_fuel_generator>);
recipes.remove(<industrialforegoing:resourceful_furnace>);
recipes.remove(<industrialforegoing:energy_field_provider>);
recipes.remove(<industrialforegoing:villager_trade_exchanger>);
recipes.remove(<industrialforegoing:fluiddictionary_converter>);
recipes.remove(<industrialforegoing:froster>);
recipes.remove(<industrialforegoing:ore_washer>);
recipes.remove(<industrialforegoing:black_hole_controller>);
recipes.remove(<industrialforegoing:ore_processor>);
recipes.remove(<industrialforegoing:laser_drill>);
recipes.remove(<industrialforegoing:laser_base>);
recipes.remove(<industrialforegoing:biofuel_generator>);
recipes.remove(<industrialforegoing:lava_fabricator>);
recipes.remove(<industrialforegoing:mob_detector>);
recipes.remove(<industrialforegoing:sludge_refiner>);
recipes.remove(<industrialforegoing:black_hole_unit>);
recipes.remove(<industrialforegoing:water_condensator>);
recipes.remove(<industrialforegoing:water_resources_collector>);
recipes.remove(<industrialforegoing:crop_enrich_material_injector>);
recipes.remove(<industrialforegoing:crop_recolector>);
recipes.remove(<industrialforegoing:animal_byproduct_recolector>);
recipes.remove(<industrialforegoing:sewage_composter_solidifier>);
recipes.remove(<industrialforegoing:latex_processing_unit>);
recipes.remove(<industrialforegoing:tree_fluid_extractor>);
recipes.remove(<industrialforegoing:block_placer>);
recipes.remove(<industrialforegoing:block_destroyer>);
recipes.remove(<industrialforegoing:mob_duplicator>);
recipes.remove(<industrialforegoing:mob_slaughter_factory>);
recipes.remove(<teslacorelib:speed_tier2>);
recipes.remove(<teslacorelib:speed_tier1>);
recipes.remove(<teslacorelib:energy_tier2>);
recipes.remove(<teslacorelib:energy_tier1>);
recipes.remove(<teslacorelib:base_addon>);
recipes.remove(<industrialforegoing:bioreactor>);
recipes.remove(<industrialforegoing:ore_sieve>);
recipes.remove(<teslacorelib:machine_case>);
recipes.remove(<industrialforegoing:black_hole_controller_reworked>);
//add


//pinkslime

mods.thermalexpansion.Transposer.addFillRecipe(<industrialforegoing:pink_slime>, <minecraft:slime_ball>, <liquid:if.pink_slime> * 250, 100);

recipes.addShaped(<industrialforegoing:range_addon:11>, [[<actuallyadditions:item_crystal:4>, <industrialforegoing:plastic>, <actuallyadditions:item_crystal:4>],[<actuallyadditions:item_crystal:4>, <industrialforegoing:range_addon:10>, <actuallyadditions:item_crystal:4>], [<actuallyadditions:item_crystal:4>, <industrialforegoing:plastic>, <actuallyadditions:item_crystal:4>]]);
recipes.addShaped(<industrialforegoing:range_addon:10>, [[<thermalfoundation:material:134>, <industrialforegoing:plastic>, <thermalfoundation:material:134>],[<thermalfoundation:material:134>, <industrialforegoing:range_addon:9>, <thermalfoundation:material:134>], [<thermalfoundation:material:134>, <industrialforegoing:plastic>, <thermalfoundation:material:134>]]);
recipes.addShaped(<industrialforegoing:range_addon:9>, [[<actuallyadditions:item_crystal:2>, <industrialforegoing:plastic>, <actuallyadditions:item_crystal:2>],[<actuallyadditions:item_crystal:2>, <industrialforegoing:range_addon:8>, <actuallyadditions:item_crystal:2>], [<actuallyadditions:item_crystal:2>, <industrialforegoing:plastic>, <actuallyadditions:item_crystal:2>]]);
recipes.addShaped(<industrialforegoing:range_addon:8>, [[<minecraft:quartz>, <industrialforegoing:plastic>, <minecraft:quartz>],[<minecraft:quartz>, <industrialforegoing:range_addon:7>, <minecraft:quartz>], [<minecraft:quartz>, <industrialforegoing:plastic>, <minecraft:quartz>]]);
recipes.addShaped(<industrialforegoing:range_addon:7>, [[<thermalfoundation:material:161>, <industrialforegoing:plastic>, <thermalfoundation:material:161>],[<thermalfoundation:material:161>, <industrialforegoing:range_addon:6>, <thermalfoundation:material:161>], [<thermalfoundation:material:161>, <industrialforegoing:plastic>, <thermalfoundation:material:161>]]);
recipes.addShaped(<industrialforegoing:range_addon:6>, [[<thermalfoundation:material:130>, <industrialforegoing:plastic>, <thermalfoundation:material:130>],[<thermalfoundation:material:130>, <industrialforegoing:range_addon:5>, <thermalfoundation:material:130>], [<thermalfoundation:material:130>, <industrialforegoing:plastic>, <thermalfoundation:material:130>]]);
recipes.addShaped(<industrialforegoing:range_addon:5>, [[<thermalfoundation:material:163>, <industrialforegoing:plastic>, <thermalfoundation:material:163>],[<thermalfoundation:material:163>, <industrialforegoing:range_addon:4>, <thermalfoundation:material:163>], [<thermalfoundation:material:163>, <industrialforegoing:plastic>, <thermalfoundation:material:163>]]);
recipes.addShaped(<industrialforegoing:range_addon:4>, [[<thermalfoundation:material:128>, <industrialforegoing:plastic>, <thermalfoundation:material:128>],[<thermalfoundation:material:128>, <industrialforegoing:range_addon:3>, <thermalfoundation:material:128>], [<thermalfoundation:material:128>, <industrialforegoing:plastic>, <thermalfoundation:material:128>]]);
recipes.addShaped(<industrialforegoing:range_addon:3>, [[<thermalfoundation:material:129>, <industrialforegoing:plastic>, <thermalfoundation:material:129>],[<thermalfoundation:material:129>, <industrialforegoing:range_addon:2>, <thermalfoundation:material:129>], [<thermalfoundation:material:129>, <industrialforegoing:plastic>, <thermalfoundation:material:129>]]);
recipes.addShaped(<industrialforegoing:range_addon:2>, [[<actuallyadditions:item_crystal:5>, <industrialforegoing:plastic>, <actuallyadditions:item_crystal:5>],[<actuallyadditions:item_crystal:5>, <industrialforegoing:range_addon:1>, <actuallyadditions:item_crystal:5>], [<actuallyadditions:item_crystal:5>, <industrialforegoing:plastic>, <actuallyadditions:item_crystal:5>]]);
recipes.addShaped(<industrialforegoing:range_addon:1>, [[<actuallyadditions:item_crystal:1>, <industrialforegoing:plastic>, <actuallyadditions:item_crystal:1>],[<actuallyadditions:item_crystal:1>, <industrialforegoing:range_addon>, <actuallyadditions:item_crystal:1>], [<actuallyadditions:item_crystal:1>, <industrialforegoing:plastic>, <actuallyadditions:item_crystal:1>]]);
recipes.addShaped(<industrialforegoing:range_addon>, [[<botania:shimmerrock>, <industrialforegoing:plastic>, <botania:shimmerrock>],[<botania:shimmerrock>, null, <botania:shimmerrock>], [<botania:shimmerrock>, <industrialforegoing:plastic>, <botania:shimmerrock>]]);
recipes.addShaped(<industrialforegoing:conveyor>*4, [[<industrialforegoing:plastic>, <industrialforegoing:plastic>, <industrialforegoing:plastic>],[<actuallyadditions:item_crystal:5>, <actuallyadditions:item_crystal>, <actuallyadditions:item_crystal:5>], [<industrialforegoing:plastic>, <industrialforegoing:plastic>, <industrialforegoing:plastic>]]);
recipes.addShaped(<industrialforegoing:adult_filter>, [[<thermalfoundation:material:161>, <industrialforegoing:plastic>, <thermalfoundation:material:161>],[<thermalfoundation:material:161>, <minecraft:egg>, <thermalfoundation:material:161>], [<thermalfoundation:material:161>, <industrialforegoing:plastic>, <thermalfoundation:material:161>]]);
recipes.addShaped(<industrialforegoing:energy_field_addon>, [[<actuallyadditions:item_crystal>, <enderio:item_alloy_endergy_ingot:4>, <actuallyadditions:item_crystal>],[<enderio:item_alloy_endergy_ingot:4>, <industrialforegoing:range_addon:9>, <enderio:item_alloy_endergy_ingot:4>], [<actuallyadditions:item_crystal>, <enderio:item_alloy_endergy_ingot:4>, <actuallyadditions:item_crystal>]]);
recipes.addShaped(<industrialforegoing:leaf_shearing>, [[<thermalfoundation:material:161>, <industrialforegoing:plastic>, <thermalfoundation:material:161>],[<thermalfoundation:material:161>, <thermalfoundation:tool.shears_platinum>, <thermalfoundation:material:161>], [<thermalfoundation:material:161>, <industrialforegoing:plastic>, <thermalfoundation:material:161>]]);
recipes.addShaped(<industrialforegoing:fortune_addon>, [[<actuallyadditions:item_crystal:4>, <industrialforegoing:plastic>, <actuallyadditions:item_crystal:4>],[<actuallyadditions:item_crystal:4>, <enderio:item_alloy_endergy_ingot:4>, <actuallyadditions:item_crystal:4>], [<actuallyadditions:item_crystal:4>, <industrialforegoing:plastic>, <actuallyadditions:item_crystal:4>]]);
recipes.addShaped(<industrialforegoing:meat_feeder>, [[<industrialforegoing:plastic>, <actuallyadditions:item_crystal:5>, <industrialforegoing:plastic>],[<minecraft:glass_bottle>, <actuallyadditions:item_crystal:5>, <minecraft:glass_bottle>], [null, <actuallyadditions:item_crystal:5>, null]]);
recipes.addShaped(<industrialforegoing:mob_imprisonment_tool>, [[null, <industrialforegoing:plastic>, null],[<industrialforegoing:plastic>, <minecraft:ghast_tear>, <industrialforegoing:plastic>], [null, <industrialforegoing:plastic>, null]]);
recipes.addShaped(<industrialforegoing:conveyor_upgrade>, [[<actuallyadditions:item_crystal:5>, <industrialforegoing:plastic>, <actuallyadditions:item_crystal:5>],[<actuallyadditions:item_crystal:5>, <minecraft:dropper>, <actuallyadditions:item_crystal:5>], [<actuallyadditions:item_crystal:5>, <industrialforegoing:conveyor>, <actuallyadditions:item_crystal:5>]]);
recipes.addShaped(<industrialforegoing:conveyor_upgrade:1>, [[<actuallyadditions:item_crystal:5>, <industrialforegoing:plastic>, <actuallyadditions:item_crystal:5>],[<actuallyadditions:item_crystal:5>, <minecraft:hopper>, <actuallyadditions:item_crystal:5>], [<actuallyadditions:item_crystal:5>, <industrialforegoing:conveyor>, <actuallyadditions:item_crystal:5>]]);
recipes.addShaped(<industrialforegoing:conveyor_upgrade:2>, [[<actuallyadditions:item_crystal:5>, <minecraft:stone_pressure_plate>, <actuallyadditions:item_crystal:5>],[<actuallyadditions:item_crystal:5>, <minecraft:comparator>, <actuallyadditions:item_crystal:5>], [<actuallyadditions:item_crystal:5>, <industrialforegoing:conveyor>, <actuallyadditions:item_crystal:5>]]);
recipes.addShaped(<industrialforegoing:conveyor_upgrade:3>, [[<actuallyadditions:item_crystal:5>, <minecraft:slime>, <actuallyadditions:item_crystal:5>],[<actuallyadditions:item_crystal:5>, <minecraft:piston>, <actuallyadditions:item_crystal:5>], [<actuallyadditions:item_crystal:5>, <industrialforegoing:conveyor>, <actuallyadditions:item_crystal:5>]]);
recipes.addShaped(<industrialforegoing:conveyor_upgrade:4>, [[<actuallyadditions:item_crystal:5>, <ore:barsIron>, <actuallyadditions:item_crystal:5>],[<actuallyadditions:item_crystal:5>, <minecraft:dropper>, <actuallyadditions:item_crystal:5>], [<actuallyadditions:item_crystal:5>, <industrialforegoing:conveyor>, <actuallyadditions:item_crystal:5>]]);
recipes.addShaped(<industrialforegoing:conveyor_upgrade:5>, [[<actuallyadditions:item_crystal:5>, <ore:listAllfruit>, <actuallyadditions:item_crystal:5>],[<actuallyadditions:item_crystal:5>, <minecraft:piston>, <actuallyadditions:item_crystal:5>], [<actuallyadditions:item_crystal:5>, <industrialforegoing:conveyor>, <actuallyadditions:item_crystal:5>]]);
recipes.addShaped(<industrialforegoing:conveyor_upgrade:6>, [[<actuallyadditions:item_crystal:5>, <industrialforegoing:conveyor>, <actuallyadditions:item_crystal:5>],[<actuallyadditions:item_crystal:5>, <minecraft:hopper>, <actuallyadditions:item_crystal:5>], [<actuallyadditions:item_crystal:5>, <industrialforegoing:conveyor>, <actuallyadditions:item_crystal:5>]]);
recipes.addShaped(<industrialforegoing:crop_sower>, [[<industrialforegoing:plastic>, <minecraft:flower_pot>, <industrialforegoing:plastic>],[<minecraft:piston>, <teslacorelib:machine_case>, <minecraft:piston>], [<thermalfoundation:material:24>, <actuallyadditions:item_crystal>, <thermalfoundation:material:24>]]);
recipes.addShaped(<industrialforegoing:animal_stock_increaser>, [[<industrialforegoing:plastic>, <minecraft:golden_apple>, <industrialforegoing:plastic>],[<minecraft:golden_carrot>, <teslacorelib:machine_case>, <minecraft:golden_carrot>], [<ore:dyePurple>, <thermalfoundation:material:24>, <ore:dyePurple>]]);
recipes.addShaped(<industrialforegoing:animal_independence_selector>, [[<industrialforegoing:plastic>, <actuallyadditions:item_crystal:4>, <industrialforegoing:plastic>],[<actuallyadditions:item_crystal:4>, <teslacorelib:machine_case>, <actuallyadditions:item_crystal:4>], [<ore:dyePurple>, <thermalfoundation:material:25>, <ore:dyePurple>]]);
recipes.addShaped(<industrialforegoing:potion_enervator>, [[<industrialforegoing:plastic>, <minecraft:brewing_stand>, <industrialforegoing:plastic>],[<thermalfoundation:material:25>, <teslacorelib:machine_case>, <thermalfoundation:material:25>], [<minecraft:repeater>, <thermalfoundation:material:25>, <minecraft:repeater>]]);
recipes.addShaped(<industrialforegoing:mob_relocator>, [[<industrialforegoing:plastic>, <actuallyadditions:item_sword_crystal_white>, <industrialforegoing:plastic>],[<minecraft:writable_book>, <teslacorelib:machine_case>, <minecraft:writable_book>], [<thermalfoundation:material:25>, <actuallyadditions:item_crystal>, <thermalfoundation:material:25>]]);
recipes.addShaped(<industrialforegoing:enchantment_aplicator>, [[<industrialforegoing:plastic>, <industrialforegoing:plastic>, <industrialforegoing:plastic>],[<enderio:block_dark_steel_anvil>, <teslacorelib:machine_case>, <enderio:block_dark_steel_anvil>], [<thermalfoundation:material:24>, <enderio:block_dark_steel_anvil>, <thermalfoundation:material:24>]]);
recipes.addShaped(<industrialforegoing:enchantment_extractor>, [[<industrialforegoing:plastic>, <minecraft:nether_brick>, <industrialforegoing:plastic>],[<minecraft:writable_book>, <teslacorelib:machine_case>, <minecraft:writable_book>], [<actuallyadditions:item_crystal:2>, <thermalfoundation:material:25>, <actuallyadditions:item_crystal:2>]]);
recipes.addShaped(<industrialforegoing:enchantment_refiner>, [[<industrialforegoing:plastic>, <actuallyadditions:block_misc:8>, <industrialforegoing:plastic>],[<minecraft:writable_book>, <teslacorelib:machine_case>, <minecraft:writable_book>], [<industrialforegoing:plastic>, <thermalfoundation:material:26>, <industrialforegoing:plastic>]]);
recipes.addShaped(<industrialforegoing:petrified_fuel_generator>, [[<industrialforegoing:plastic>, <actuallyadditions:item_crystal:2>, <industrialforegoing:plastic>],[<thermalfoundation:material:25>, <teslacorelib:machine_case>, <thermalfoundation:material:25>], [<industrialforegoing:plastic>, <tconstruct:seared_furnace_controller>, <industrialforegoing:plastic>]]);
recipes.addShaped(<industrialforegoing:spores_recreator>, [[<industrialforegoing:plastic>, <industrialforegoing:plastic>, <industrialforegoing:plastic>],[<minecraft:red_mushroom>, <teslacorelib:machine_case>, <minecraft:red_mushroom>], [<industrialforegoing:plastic>, <thermalfoundation:material:24>, <industrialforegoing:plastic>]]);
recipes.addShaped(<industrialforegoing:enchantment_invoker>, [[<industrialforegoing:plastic>, <minecraft:writable_book>, <industrialforegoing:plastic>],[<actuallyadditions:item_crystal:2>, <teslacorelib:machine_case>, <actuallyadditions:item_crystal:2>], [<enderio:block_reinforced_obsidian>, <enderio:block_reinforced_obsidian>, <enderio:block_reinforced_obsidian>]]);
recipes.addShaped(<industrialforegoing:dye_mixer>, [[<industrialforegoing:plastic>, <ore:dyeGreen>, <industrialforegoing:plastic>],[<ore:dyeRed>, <teslacorelib:machine_case>, <ore:gemLapis>], [<industrialforegoing:plastic>, <thermalfoundation:material:25>, <industrialforegoing:plastic>]]);

recipes.addShaped(<industrialforegoing:black_hole_tank>, [[<industrialforegoing:plastic>, <industrialforegoing:plastic>, <industrialforegoing:plastic>],[<minecraft:ender_eye>, <actuallyadditions:block_misc:8>, <minecraft:ender_eye>], [<botania:openbucket>, <teslacorelib:machine_case>, <botania:openbucket>]]);
recipes.addShaped(<industrialforegoing:material_stonework_factory>, [[<industrialforegoing:plastic>, <projectred-expansion:machine2:10>, <industrialforegoing:plastic>],[<actuallyadditions:item_pickaxe_crystal_white>, <teslacorelib:machine_case>, <tconstruct:seared_furnace_controller>], [<minecraft:lava_bucket>, <industrialforegoing:pink_slime>, <minecraft:water_bucket>]]);
recipes.addShaped(<industrialforegoing:animal_growth_increaser>, [[<industrialforegoing:plastic>, <minecraft:wheat>, <industrialforegoing:plastic>],[<minecraft:wheat>, <teslacorelib:machine_case>, <minecraft:wheat>], [<ore:dyePurple>, <thermalfoundation:material:25>, <ore:dyePurple>]]);
recipes.addShaped(<industrialforegoing:fluid_crafter>, [[<industrialforegoing:plastic>, <projectred-expansion:machine2:10>, <industrialforegoing:plastic>],[<botania:openbucket>, <teslacorelib:machine_case>, <botania:openbucket>], [<industrialforegoing:plastic>, <thermalfoundation:material:25>, <industrialforegoing:plastic>]]);
recipes.addShaped(<industrialforegoing:plant_interactor>, [[<industrialforegoing:plastic>, <actuallyadditions:item_hoe_crystal_white>, <industrialforegoing:plastic>],[<actuallyadditions:item_hoe_crystal_white>, <teslacorelib:machine_case>, <actuallyadditions:item_hoe_crystal_white>], [<thermalfoundation:material:25>, <actuallyadditions:item_crystal>, <thermalfoundation:material:25>]]);
recipes.addShaped(<industrialforegoing:item_splitter>, [[<industrialforegoing:plastic>, <actuallyadditions:block_giant_chest>, <industrialforegoing:plastic>],[<minecraft:hopper>, <teslacorelib:machine_case>, <minecraft:hopper>], [<industrialforegoing:plastic>, <thermalfoundation:material:24>, <industrialforegoing:plastic>]]);
recipes.addShaped(<industrialforegoing:animal_resource_harvester>, [[<industrialforegoing:plastic>, <industrialforegoing:plastic>, <industrialforegoing:plastic>],[<thermalfoundation:tool.shears_platinum>, <botania:openbucket>, <thermalfoundation:tool.shears_platinum>], [<thermalfoundation:material:25>, <teslacorelib:machine_case>, <thermalfoundation:material:25>]]);
recipes.addShaped(<industrialforegoing:fluid_pump>, [[<industrialforegoing:plastic>, <botania:openbucket>, <industrialforegoing:plastic>],[<minecraft:lava_bucket>, <teslacorelib:machine_case>, <minecraft:water_bucket>], [<industrialforegoing:plastic>, <thermalfoundation:material:25>, <industrialforegoing:plastic>]]);
recipes.addShaped(<industrialforegoing:wither_builder>, [[<industrialforegoing:plastic>, <actuallyadditions:item_misc:19>, <industrialforegoing:plastic>],[<minecraft:skull:1>, <teslacorelib:machine_case>, <minecraft:skull:1>], [<minecraft:soul_sand>, <minecraft:soul_sand>, <minecraft:soul_sand>]]);
recipes.addShaped(<industrialforegoing:hydrator>, [[<industrialforegoing:plastic>, <minecraft:water_bucket>, <industrialforegoing:plastic>],[<industrialforegoing:fertilizer>, <teslacorelib:machine_case>, <industrialforegoing:fertilizer>], [<thermalfoundation:material:24>, <minecraft:piston>, <thermalfoundation:material:24>]]);
recipes.addShaped(<industrialforegoing:protein_generator>, [[<industrialforegoing:plastic>, <tconstruct:seared_furnace_controller>, <industrialforegoing:plastic>],[<minecraft:piston>, <industrialforegoing:biofuel_generator>, <minecraft:piston>], [<minecraft:spider_eye>, <minecraft:piston>, <minecraft:spider_eye>]]);
recipes.addShaped(<industrialforegoing:oredictionary_converter>, [[<industrialforegoing:plastic>, <industrialforegoing:plastic>, <industrialforegoing:plastic>],[<industrialforegoing:plastic>, <teslacorelib:machine_case>, <industrialforegoing:plastic>], [<minecraft:iron_nugget>, <minecraft:iron_ingot>, <minecraft:iron_block>]]);
recipes.addShaped(<industrialforegoing:ore_fermenter>, [[<minecraft:iron_bars>, <botania:dreamwood>, <minecraft:iron_bars>],[<botania:dreamwood>, <thermalfoundation:material:24>, <botania:dreamwood>], [<minecraft:iron_bars>, <teslacorelib:machine_case>, <minecraft:iron_bars>]]);
recipes.addShaped(<industrialforegoing:protein_reactor>, [[<industrialforegoing:plastic>, <minecraft:porkchop>, <industrialforegoing:plastic>],[<minecraft:egg>, <teslacorelib:machine_case>, <minecraft:egg>], [<tconstruct:seared:3>, <minecraft:rabbit_foot>, <tconstruct:seared:3>]]);
recipes.addShaped(<industrialforegoing:pitiful_fuel_generator>, [[<botania:shimmerrock>, <thermalfoundation:material:161>, <botania:shimmerrock>],[<thermalfoundation:material:24>, <teslacorelib:machine_case>, <thermalfoundation:material:24>], [<botania:shimmerrock>, <tconstruct:seared_furnace_controller>, <botania:shimmerrock>]]);
recipes.addShaped(<industrialforegoing:resourceful_furnace>, [[<industrialforegoing:plastic>, <botania:openbucket>, <industrialforegoing:plastic>],[<tconstruct:seared_furnace_controller>, <teslacorelib:machine_case>, <tconstruct:seared_furnace_controller>], [<industrialforegoing:plastic>, <thermalfoundation:material:25>, <industrialforegoing:plastic>]]);
recipes.addShaped(<industrialforegoing:energy_field_provider>, [[<thermalfoundation:material:161>, <industrialforegoing:energy_field_addon>, <thermalfoundation:material:161>],[<thermalfoundation:material:161>, <teslacorelib:machine_case>, <thermalfoundation:material:161>], [<minecraft:repeater>, <thermalfoundation:material:26>, <minecraft:repeater>]]);
recipes.addShaped(<industrialforegoing:villager_trade_exchanger>, [[<industrialforegoing:plastic>, <thermalfoundation:material:161>, <industrialforegoing:plastic>],[<actuallyadditions:item_crystal:4>, <teslacorelib:machine_case>, <actuallyadditions:item_crystal:4>], [<industrialforegoing:plastic>, <thermalfoundation:material:25>, <industrialforegoing:plastic>]]);
recipes.addShaped(<industrialforegoing:fluiddictionary_converter>, [[<industrialforegoing:plastic>, <industrialforegoing:plastic>, <industrialforegoing:plastic>],[<enderio:block_fused_quartz>, <teslacorelib:machine_case>, <enderio:block_fused_quartz>], [<botania:openbucket>, <thermalfoundation:material:24>, <botania:openbucket>]]);
recipes.addShaped(<industrialforegoing:froster>, [[<industrialforegoing:plastic>, <minecraft:packed_ice>, <industrialforegoing:plastic>],[<minecraft:snow>, <teslacorelib:machine_case>, <minecraft:snow>], [<industrialforegoing:plastic>, <thermalfoundation:material:25>, <industrialforegoing:plastic>]]);
recipes.addShaped(<industrialforegoing:ore_washer>, [[<enderio:item_alloy_endergy_ingot:4>, <industrialforegoing:meat_feeder>, <enderio:item_alloy_endergy_ingot:4>],[<industrialforegoing:plastic>, <teslacorelib:machine_case>, <industrialforegoing:plastic>], [<industrialforegoing:conveyor>, <thermalfoundation:material:26>, <industrialforegoing:conveyor>]]);
recipes.addShaped(<industrialforegoing:black_hole_controller_reworked>, [[<industrialforegoing:plastic>, <actuallyadditions:block_crystal:2>, <industrialforegoing:plastic>],[<enderio:item_alloy_endergy_ingot:4>, <enderstorage:ender_storage>, <enderio:item_alloy_endergy_ingot:4>], [<industrialforegoing:plastic>, <teslacorelib:machine_case>, <industrialforegoing:plastic>]]);
recipes.addShaped(<industrialforegoing:ore_processor>, [[<industrialforegoing:plastic>, <minecraft:piston>, <industrialforegoing:plastic>],[<actuallyadditions:item_pickaxe_crystal_white>, <teslacorelib:machine_case>, <actuallyadditions:item_pickaxe_crystal_white>], [<minecraft:book>, <actuallyadditions:item_crystal>, <minecraft:book>]]);
recipes.addShaped(<industrialforegoing:laser_drill>, [[<industrialforegoing:plastic>, <industrialforegoing:laser_lens>, <industrialforegoing:plastic>],[<enderio:block_fused_quartz>, <minecraft:glowstone>, <enderio:block_fused_quartz>], [<thermalfoundation:material:26>, <teslacorelib:machine_case>, <thermalfoundation:material:26>]]);
recipes.addShaped(<industrialforegoing:laser_base>, [[<industrialforegoing:plastic>, <minecraft:glowstone>, <industrialforegoing:plastic>],[<thermalfoundation:material:25>, <minecraft:glowstone>, <thermalfoundation:material:25>], [<thermalfoundation:material:26>, <teslacorelib:machine_case>, <thermalfoundation:material:26>]]);
recipes.addShaped(<industrialforegoing:biofuel_generator>, [[<industrialforegoing:plastic>, <tconstruct:seared_furnace_controller>, <industrialforegoing:plastic>],[<minecraft:piston>, <teslacorelib:machine_case>, <minecraft:piston>], [<botania:blazeblock>, <minecraft:piston>, <botania:blazeblock>]]);
recipes.addShaped(<industrialforegoing:lava_fabricator>, [[<industrialforegoing:plastic>, <tconstruct:large_plate>.withTag({Material: "obsidian"}), <industrialforegoing:plastic>],[<minecraft:magma>, <teslacorelib:machine_case>, <minecraft:magma>], [<botania:blazeblock>, <actuallyadditions:block_crystal>, <botania:blazeblock>]]);
recipes.addShaped(<industrialforegoing:mob_detector>, [[<industrialforegoing:plastic>, <industrialforegoing:plastic>, <industrialforegoing:plastic>],[<minecraft:repeater>, <minecraft:comparator>, <minecraft:repeater>], [<minecraft:observer>, <teslacorelib:machine_case>, <minecraft:observer>]]);
recipes.addShaped(<industrialforegoing:sludge_refiner>, [[<industrialforegoing:plastic>, <botania:openbucket>, <industrialforegoing:plastic>],[<tconstruct:seared_furnace_controller>, <teslacorelib:machine_case>, <tconstruct:seared_furnace_controller>], [<thermalfoundation:material:24>, <thermalfoundation:material:25>, <thermalfoundation:material:24>]]);
recipes.addShaped(<industrialforegoing:black_hole_unit>, [[<industrialforegoing:plastic>, <industrialforegoing:plastic>, <industrialforegoing:plastic>],[<minecraft:ender_eye>, <actuallyadditions:block_misc:8>, <minecraft:ender_eye>], [<actuallyadditions:block_giant_chest>, <teslacorelib:machine_case>, <actuallyadditions:block_giant_chest>]]);
recipes.addShaped(<industrialforegoing:water_condensator>, [[<industrialforegoing:plastic>, <minecraft:water_bucket>, <industrialforegoing:plastic>],[<minecraft:piston>, <teslacorelib:machine_case>, <minecraft:piston>], [<thermalfoundation:material:24>, <actuallyadditions:item_crystal>, <thermalfoundation:material:24>]]);
recipes.addShaped(<industrialforegoing:water_resources_collector>, [[<industrialforegoing:plastic>, <thermalfoundation:tool.fishing_rod_iron>, <industrialforegoing:plastic>],[<botania:openbucket>, <teslacorelib:machine_case>, <botania:openbucket>], [<thermalfoundation:material:24>, <actuallyadditions:item_crystal>, <thermalfoundation:material:24>]]);
recipes.addShaped(<industrialforegoing:crop_enrich_material_injector>, [[<industrialforegoing:plastic>, <minecraft:glass_bottle>, <industrialforegoing:plastic>],[<minecraft:leather>, <teslacorelib:machine_case>, <minecraft:leather>], [<thermalfoundation:material:24>, <actuallyadditions:item_crystal>, <thermalfoundation:material:24>]]);
recipes.addShaped(<industrialforegoing:crop_recolector>, [[<industrialforegoing:plastic>, <actuallyadditions:item_hoe_crystal_white>, <industrialforegoing:plastic>],[<actuallyadditions:item_axe_crystal_white>, <teslacorelib:machine_case>, <actuallyadditions:item_axe_crystal_white>], [<thermalfoundation:material:25>, <actuallyadditions:item_crystal>, <thermalfoundation:material:25>]]);
recipes.addShaped(<industrialforegoing:animal_byproduct_recolector>, [[<industrialforegoing:plastic>, <botania:openbucket>, <industrialforegoing:plastic>],[<minecraft:hardened_clay>, <teslacorelib:machine_case>, <minecraft:hardened_clay>], [<tconstruct:seared:3>, <actuallyadditions:item_crystal>, <tconstruct:seared:3>]]);
recipes.addShaped(<industrialforegoing:sewage_composter_solidifier>, [[<industrialforegoing:plastic>, <tconstruct:seared_furnace_controller>, <industrialforegoing:plastic>],[<minecraft:piston>, <teslacorelib:machine_case>, <minecraft:piston>], [<tconstruct:seared:3>, <actuallyadditions:item_crystal>, <tconstruct:seared:3>]]);
recipes.addShaped(<industrialforegoing:latex_processing_unit>, [[<actuallyadditions:item_crystal:5>, <actuallyadditions:item_crystal>, <actuallyadditions:item_crystal:5>],[<tconstruct:seared_furnace_controller>, <teslacorelib:machine_case>, <tconstruct:seared_furnace_controller>], [<actuallyadditions:item_crystal:5>, <thermalfoundation:material:24>, <actuallyadditions:item_crystal:5>]]);
recipes.addShaped(<industrialforegoing:tree_fluid_extractor>, [[<botania:shimmerrock>, <actuallyadditions:item_crystal>, <botania:shimmerrock>],[<botania:shimmerrock>, <tconstruct:seared_furnace_controller>, <botania:shimmerrock>], [<botania:shimmerrock>, <thermalfoundation:material:24>, <botania:shimmerrock>]]);
recipes.addShaped(<industrialforegoing:block_placer>, [[<industrialforegoing:plastic>, <minecraft:dropper>, <industrialforegoing:plastic>],[<minecraft:dropper>, <teslacorelib:machine_case>, <minecraft:dropper>], [<industrialforegoing:plastic>, <actuallyadditions:item_crystal>, <industrialforegoing:plastic>]]);
recipes.addShaped(<industrialforegoing:block_destroyer>, [[<industrialforegoing:plastic>, <thermalfoundation:material:25>, <industrialforegoing:plastic>],[<actuallyadditions:item_pickaxe_crystal_white>, <teslacorelib:machine_case>, <actuallyadditions:item_shovel_crystal_white>], [<thermalfoundation:material:24>, <actuallyadditions:item_crystal>, <thermalfoundation:material:24>]]);
recipes.addShaped(<industrialforegoing:mob_duplicator>, [[<industrialforegoing:plastic>, <enderio:block_alloy_endergy:4>, <industrialforegoing:plastic>],[<minecraft:magma>, <teslacorelib:machine_case>, <minecraft:magma>], [<actuallyadditions:item_crystal:4>, <actuallyadditions:item_crystal>, <actuallyadditions:item_crystal:4>]]);
recipes.addShaped(<industrialforegoing:mob_slaughter_factory>, [[<industrialforegoing:plastic>, <thermalfoundation:material:25>, <industrialforegoing:plastic>],[<actuallyadditions:item_sword_crystal_white>, <teslacorelib:machine_case>, <actuallyadditions:item_sword_crystal_white>], [<actuallyadditions:item_axe_crystal_white>, <actuallyadditions:item_crystal>, <actuallyadditions:item_axe_crystal_white>]]);
recipes.addShaped(<teslacorelib:speed_tier2>, [[null, <actuallyadditions:item_crystal:2>, null],[<actuallyadditions:item_crystal:2>, <teslacorelib:speed_tier1>, <actuallyadditions:item_crystal:2>], [null, <actuallyadditions:item_crystal:2>, null]]);
recipes.addShaped(<teslacorelib:speed_tier1>, [[<actuallyadditions:item_crystal>, <thermalfoundation:material:25>, <actuallyadditions:item_crystal>],[<actuallyadditions:item_crystal>, <teslacorelib:base_addon>, <actuallyadditions:item_crystal>], [<actuallyadditions:item_crystal>, <thermalfoundation:material:25>, <actuallyadditions:item_crystal>]]);
recipes.addShaped(<teslacorelib:energy_tier2>, [[null, <actuallyadditions:item_crystal:2>, null],[<actuallyadditions:item_crystal:2>, <teslacorelib:energy_tier1>, <actuallyadditions:item_crystal:2>], [null, <actuallyadditions:item_crystal:2>, null]]);
recipes.addShaped(<teslacorelib:energy_tier1>, [[null, <thermalfoundation:material:25>, null],[<actuallyadditions:item_crystal>, <teslacorelib:base_addon>, <actuallyadditions:item_crystal>], [<actuallyadditions:item_crystal>, <actuallyadditions:item_crystal>, <actuallyadditions:item_crystal>]]);
recipes.addShaped(<teslacorelib:base_addon>, [[<tconstruct:large_plate>.withTag({Material: "paper"}), <actuallyadditions:item_crystal>, <tconstruct:large_plate>.withTag({Material: "paper"})],[<tconstruct:large_plate>.withTag({Material: "paper"}), <tconstruct:large_plate>.withTag({Material: "paper"}), <tconstruct:large_plate>.withTag({Material: "paper"})], [<tconstruct:large_plate>.withTag({Material: "paper"}), <actuallyadditions:item_crystal>, <tconstruct:large_plate>.withTag({Material: "paper"})]]);
recipes.addShaped(<industrialforegoing:bioreactor>, [[<industrialforegoing:plastic>, <minecraft:fermented_spider_eye>, <industrialforegoing:plastic>],[<tconstruct:materials:9>, <teslacorelib:machine_case>, <tconstruct:materials:9>], [<tconstruct:materials>, <vanillafoodpantry:golden_sugar>, <tconstruct:materials>]]);
recipes.addShaped(<industrialforegoing:ore_sieve>, [[<industrialforegoing:plastic>, <industrialforegoing:pink_slime>, <industrialforegoing:plastic>],[<enderio:block_dark_iron_bars>, <enderio:block_dark_iron_bars>, <enderio:block_dark_iron_bars>], [<thermalfoundation:material:289>, <teslacorelib:machine_case>, <thermalfoundation:material:289>]]);

//machine case 

mods.extendedcrafting.EnderCrafting.addShaped(<teslacorelib:machine_case>, [[<actuallyadditions:item_crystal:5>, <thaumcraft:plank_greatwood>, <actuallyadditions:item_crystal:5>],[<thaumcraft:plank_greatwood>, <actuallyadditions:block_crystal>, <thaumcraft:plank_greatwood>], [<actuallyadditions:item_crystal:5>, <thaumcraft:plank_greatwood>, <actuallyadditions:item_crystal:5>]]);
mods.extendedcrafting.EnderCrafting.addShaped(<teslacorelib:machine_case>, [[<actuallyadditions:item_crystal:5>, <thaumcraft:plank_silverwood>, <actuallyadditions:item_crystal:5>],[<thaumcraft:plank_silverwood>, <actuallyadditions:block_crystal>, <thaumcraft:plank_silverwood>], [<actuallyadditions:item_crystal:5>, <thaumcraft:plank_silverwood>, <actuallyadditions:item_crystal:5>]]);
